FPO-290
trade-tariff/trade-tariff-dev-hub-backend pull request #47
Opened 2024-06-25 12:30 UTC by Lee365

### Jira link
https://transformuk.atlassian.net/browse/FPO-290

### What?

I have added/removed/altered:

- [x] Added
- [x] Removed
- [x] Altered

### Why?

I am doing this because:

-

### AC

- Tested
- Shared with stakeholders
- Pair reviewed

2024-06-26 12:31 UTC, ashward commented on src/controllers/apiKeysController.ts
> +    const applicationReference = req.body.applicationReference
What do we need the `applicationReference` for when creating a new API key? Doesn't seem to be used anywhere.

2024-06-26 12:31 UTC, ashward commented on spec/controllers/apiKeysControllerSpec.ts
> -      const res = {
Any reason this chunk of the test has been deleted?

2024-06-26 13:27 UTC, Lee365 commented on spec/controllers/apiKeysControllerSpec.ts
> -      const res = {
Mmm . not sure. Added this back.

2024-06-26 13:30 UTC, Lee365 commented on src/controllers/apiKeysController.ts
> +    const applicationReference = req.body.applicationReference
Removed

2024-06-27 08:28 UTC, ashward commented on src/operations/updateOrganisation.ts
> +const TableName = process.env.ORGANISATIONS_TABLE_NAME ?? ''
Shouldn't we default this? Seems a bit much to require such a basic thing to be configured?

2024-06-27 08:29 UTC, ashward commented on src/operations/updateOrganisation.ts
> +const TableName = process.env.ORGANISATIONS_TABLE_NAME ?? ''
Also variable/const names should be camelCase

2024-06-27 08:48 UTC, Lee365 commented on src/operations/updateOrganisation.ts
> +const TableName = process.env.ORGANISATIONS_TABLE_NAME ?? ''
export interface UpdateItemInput 
    TableName: string | undefined;

2024-06-27 08:48 UTC, merged

2024-06-27 08:49 UTC, mkayad requested changes

2024-06-27 08:49 UTC, mkayad commented on src/routes/api.ts
> +router.patch('/organisation/:organisationId', (req, res) => { userController.updateOrganisation(req, res) })
I think the path should be plural to be consistent with the rest of routes.